"use strict";
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
Object.defineProperty(exports, "__esModule", { value: true });
const express_1 = __importDefault(require("express"));
const cors_1 = __importDefault(require("cors"));
const path_1 = __importDefault(require("path"));
require("dotenv/config");
require("express-async-errors");
// import bodyParser from 'body-parser';
require("./database/connection");
const routes_1 = __importDefault(require("./routes"));
const handler_1 = __importDefault(require("./Errors/handler"));
const app = express_1.default();
app.use(cors_1.default({ origin: '*' }));
app.use(express_1.default.json());
app.use(routes_1.default);
app.use('/uploads', express_1.default.static(path_1.default.join(__dirname, 'uploads')));
app.use(handler_1.default);
const port = process.env.PORT || 3333;
app.listen(port, () => console.log('Server is running on port: ' + port));
